# Form implementation generated from reading ui file 'recallWin.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 700)
        MainWindow.setMaximumSize(QtCore.QSize(385, 700))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 600, 385, 16))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 385, 16))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 385, 76))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.ico_rating = QtWidgets.QLabel(parent=self.frame)
        self.ico_rating.setGeometry(QtCore.QRect(315, 10, 50, 50))
        self.ico_rating.setStyleSheet("image: url(:/resources/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/фон+шрифты+верх.панель/рейтинг.ico);")
        self.ico_rating.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ico_rating.setText("")
        self.ico_rating.setObjectName("ico_rating")
        self.place_rating = QtWidgets.QLabel(parent=self.frame)
        self.place_rating.setGeometry(QtCore.QRect(255, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Aristotelica Pro Tx Extlt")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.place_rating.setFont(font)
        self.place_rating.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.place_rating.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.place_rating.setObjectName("place_rating")
        self.count_days = QtWidgets.QLabel(parent=self.frame)
        self.count_days.setGeometry(QtCore.QRect(10, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Aristotelica Pro Tx Extlt")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.count_days.setFont(font)
        self.count_days.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.count_days.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.count_days.setObjectName("count_days")
        self.ico_days = QtWidgets.QLabel(parent=self.frame)
        self.ico_days.setGeometry(QtCore.QRect(60, 10, 50, 50))
        self.ico_days.setAutoFillBackground(False)
        self.ico_days.setStyleSheet("image: url(:/resources/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/фон+шрифты+верх.панель/огонёк.ico);")
        self.ico_days.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ico_days.setText("")
        self.ico_days.setObjectName("ico_days")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 610, 385, 90))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_book = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_book.setGeometry(QtCore.QRect(230, 10, 70, 70))
        self.btn_book.setStyleSheet("QPushButton {\n"
"image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 4.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_book.setText("")
        self.btn_book.setObjectName("btn_book")
        self.btn_home = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_home.setGeometry(QtCore.QRect(5, 10, 70, 70))
        self.btn_home.setStyleSheet("QPushButton {\n"
"    image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 1.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_home.setText("")
        self.btn_home.setObjectName("btn_home")
        self.btn_settings = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_settings.setGeometry(QtCore.QRect(305, 10, 70, 70))
        self.btn_settings.setStyleSheet("QPushButton {\n"
"image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 5.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setObjectName("btn_settings")
        self.btn_recall = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_recall.setGeometry(QtCore.QRect(155, 10, 70, 70))
        self.btn_recall.setStyleSheet("QPushButton {\n"
"image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 3.2.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_recall.setText("")
        self.btn_recall.setObjectName("btn_recall")
        self.btn_rating = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_rating.setGeometry(QtCore.QRect(80, 10, 70, 70))
        self.btn_rating.setStyleSheet("QPushButton {\n"
"image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 2.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_rating.setText("")
        self.btn_rating.setObjectName("btn_rating")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 80, 385, 525))
        self.frame_3.setStyleSheet("background-image: url(:/resources/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/фон+шрифты+верх.панель/фон.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 80, 331, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 8.3.ico);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_5.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 9.1.ico);\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_3.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 6.3.ico);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_4.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 2.3.ico);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 1.3.ico);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_6.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 4.3.ico);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 3.1.ico);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_8.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 5.3.ico);")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setStyleSheet("border: none;\n"
"image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/иконка 7.3.ico);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(79, 10, 281, 61))
        self.label.setStyleSheet("image: url(:/mainmenu/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/2. главное меню/1. текст .ico);")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.place_rating.setText(_translate("MainWindow", "0"))
        self.count_days.setText(_translate("MainWindow", "0"))
