# Form implementation generated from reading ui file 'settingsWin.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 700)
        MainWindow.setMaximumSize(QtCore.QSize(385, 700))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 600, 385, 16))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 385, 16))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 385, 76))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.ico_rating = QtWidgets.QLabel(parent=self.frame)
        self.ico_rating.setGeometry(QtCore.QRect(315, 10, 50, 50))
        self.ico_rating.setStyleSheet("image: url(:/resources/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/фон+шрифты+верх.панель/рейтинг.ico);")
        self.ico_rating.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ico_rating.setText("")
        self.ico_rating.setObjectName("ico_rating")
        self.place_rating = QtWidgets.QLabel(parent=self.frame)
        self.place_rating.setGeometry(QtCore.QRect(255, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Aristotelica Pro Tx Extlt")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.place_rating.setFont(font)
        self.place_rating.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.place_rating.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.place_rating.setObjectName("place_rating")
        self.count_days = QtWidgets.QLabel(parent=self.frame)
        self.count_days.setGeometry(QtCore.QRect(10, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Aristotelica Pro Tx Extlt")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.count_days.setFont(font)
        self.count_days.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.count_days.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.count_days.setObjectName("count_days")
        self.ico_days = QtWidgets.QLabel(parent=self.frame)
        self.ico_days.setGeometry(QtCore.QRect(60, 10, 50, 50))
        self.ico_days.setAutoFillBackground(False)
        self.ico_days.setStyleSheet("image: url(:/resources/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/фон+шрифты+верх.панель/огонёк.ico);")
        self.ico_days.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ico_days.setText("")
        self.ico_days.setObjectName("ico_days")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 610, 385, 90))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_book = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_book.setGeometry(QtCore.QRect(230, 10, 70, 70))
        self.btn_book.setStyleSheet("QPushButton {\n"
"    image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 4.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_book.setText("")
        self.btn_book.setObjectName("btn_book")
        self.btn_home = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_home.setGeometry(QtCore.QRect(5, 10, 70, 70))
        self.btn_home.setStyleSheet("QPushButton {\n"
"    image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 1.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_home.setText("")
        self.btn_home.setObjectName("btn_home")
        self.btn_settings = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_settings.setGeometry(QtCore.QRect(305, 10, 70, 70))
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 5.2.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_settings.setText("")
        self.btn_settings.setObjectName("btn_settings")
        self.btn_recall = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_recall.setGeometry(QtCore.QRect(155, 10, 70, 70))
        self.btn_recall.setStyleSheet("QPushButton {\n"
"    image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 3.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_recall.setText("")
        self.btn_recall.setObjectName("btn_recall")
        self.btn_rating = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_rating.setGeometry(QtCore.QRect(80, 10, 70, 70))
        self.btn_rating.setStyleSheet("QPushButton {\n"
"    image: url(:/bottom/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/нижняя панель/н.п. 2.1.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_rating.setText("")
        self.btn_rating.setObjectName("btn_rating")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 80, 385, 525))
        self.frame_3.setStyleSheet("background-image: url(:/resources/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/фон+шрифты+верх.панель/фон.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_chat = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_chat.setGeometry(QtCore.QRect(5, 450, 70, 70))
        self.btn_chat.setStyleSheet("QPushButton {\n"
"    image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/иконка чата.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_chat.setText("")
        self.btn_chat.setObjectName("btn_chat")
        self.btn_exit = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_exit.setGeometry(QtCore.QRect(305, 450, 70, 70))
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/иконка выхода.ico);\n"
"    color: black;\n"
"    border-radius: 35px;\n"
"}")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.photo_profile = QtWidgets.QLabel(parent=self.frame_3)
        self.photo_profile.setGeometry(QtCore.QRect(15, 15, 100, 100))
        self.photo_profile.setStyleSheet("image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/иконка профиля.ico);")
        self.photo_profile.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.photo_profile.setText("")
        self.photo_profile.setObjectName("photo_profile")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(124, 40, 240, 47))
        font = QtGui.QFont()
        font.setFamily("Kudryashev Display")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/фон под фио.ico);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(124, 180, 240, 330))
        self.frame_4.setStyleSheet("QFrame {\n"
"image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/8.1. достижения.ico);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"    border-radius: 15px;  \n"
"}\n"
"QFrame QLabel {\n"
"    border: none;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Kudryashev Display")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/8.1. фон под процент.ico);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ico_days_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.ico_days_2.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.ico_days_2.setAutoFillBackground(False)
        self.ico_days_2.setStyleSheet("image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/огонёк.ico);")
        self.ico_days_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ico_days_2.setText("")
        self.ico_days_2.setObjectName("ico_days_2")
        self.ico_rating_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.ico_rating_2.setGeometry(QtCore.QRect(20, 100, 50, 50))
        self.ico_rating_2.setStyleSheet("image: url(:/profile/C:/Users/Фёдор/PycharmProjects/Bushe/MyIcons/9. профиль/рейтинг.ico);")
        self.ico_rating_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ico_rating_2.setText("")
        self.ico_rating_2.setObjectName("ico_rating_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(89, 10, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Kudryashev Display")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(89, 100, 131, 50))
        font = QtGui.QFont()
        font.setFamily("Kudryashev Display")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(89, 180, 131, 50))
        font = QtGui.QFont()
        font.setFamily("Kudryashev Display")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.place_rating.setText(_translate("MainWindow", "0"))
        self.count_days.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Имя Кличка"))
        self.label_2.setText(_translate("MainWindow", "30%"))
        self.label_3.setText(_translate("MainWindow", "31 день \n"
"ты занимаешься\n"
"без перерыва"))
        self.label_4.setText(_translate("MainWindow", "2 место в рейтинге"))
        self.label_5.setText(_translate("MainWindow", "Процент усвоения\n"
"материала"))
